random_seed: 1234
verbose: yes
mode: quantum # classical or quantum
classical:
  layers: 2
  neurons: 8
quantum:
  layers: 4
  qubits: 8
  entanglement: full #ladder, double ladder, brick, full
  rotations: [[x, y, z], [y], [x], [z, x]] # [(x, y), (x, y), (x, y), (x, y)]
  entanglements: [full, full, ladder, brick]
  brick_size: 4
environment:
  name: MountainCar-v0 # CartPole-v1 or MountainCar-v0
  render_mode: human
  render: no
memory_size: 100000
training:
  batch_size: 64
  optimizer: adam
  loss: mse
  max_steps: 200
  episodes: 1000
  epsilon:
    end: 0.01
    start: 0.2

    change: 1
