random_seed: 1234
verbose: yes
mode: quantum # classical or quantum
memory_size: 100000
trials_per_configuration: 3
classical:
  layers: 2
  neurons: 64
quantum:
  layers: 1
  qubits: 4
  rotations: [ [ x,y, z] ,[ x,y ] ]
  entanglements: [ ladder, ladder, none, noner ] #ladder, double ladder, brick, full
  brick_size: 4
  bounds:
    layers: [ 1, 4 ]
    qubits: [ 1, 5 ]
    rotations: [ x, y ]
    entanglements: [ ladder, full, none ] #ladder, double ladder, brick, full
    brick_size: [ 3 ]
environment:
  name: CartPole-v1 # CartPole-v1 or MountainCar-v0
  render_mode: human
  render: no
training:
  batch_size: 16
  optimizer: adam
  loss: mse
  max_steps: 200
  episodes: 1000
  epsilon:
    end: 0.01
    start: 0.2
    change: 1
