random_seed: 1234
verbose: no
mode: quantum # classical or quantum
classical:
  layers: 2
  neurons: 64
quantum:
  layers: 4
  qubits: 5
environment:
  name: CartPole-v1
  render_mode: human
  render: no
memory_size: 100000
training:
  batch_size: 64
  optimizer: adam
  loss: mse
  max_steps: 200
  episodes: 1000
  epsilon:
    end: 0.01
    start: 0.2
    change: 1
