random_seed: 1234
verbose: no
cluster: no
mode: quantum # classical or quantum
memory_size: 2000
trials_per_configuration: 3
classical:
  layers: 2
  neurons: 64
  bounds:
    layers: [ 1,2,3,4 ]
    neurons: [ 32, 64, 128, 256 ]
    learning_rate: [ 0.1, 0.03, 0.01, 0.003, 0.001 ]
quantum:
  layers:
  qubits: 6
  rotations: [ [ x, y, z ] ]
  entanglements: [ none ] #ladder, double ladder, brick, full
  brick_size: 4
  learning_rate: 0.01
  bounds:
    layers: [ 1,2,3,4 ]
    qubits: [ 6 ]
    rotations: [ [ x, y ] ]
    entanglements: [ ladder, double ladder, full, none ] # brick
    learning_rate: [ 0.1, 0.03, 0.01, 0.003, 0.001 ]
environment:
  name: Acrobot-v1 # CartPole-v1, Acrobot-v1 or MountainCar-v0
  render_mode: human
  render: no
training:
  early_stop: 20
  batch_size: 8
  optimizer: adam
  loss: mse
  max_steps: 100
  episodes: 1000
  epsilon:
    end: 0.01
    start: 1
    change: .996
