random_seed: 1234
verbose: no
mode: classical # classical or quantum
classical:
  layers: 2
  neurons: 16
quantum:
  layers: 4
  qubits: 5
environment:
  name: MountainCar-v0
  render_mode: human
  render: yes
memory_size: 100000
training:
  batch_size: 8
  optimizer: adam
  loss: mse
  max_steps: 200
  episodes: 20
  epsilon:
    end: 0.01
    start: 0.2
    change: 1
