random_seed: 1234
verbose: yes
cluster: no
mode: quantum # classical or quantum
memory_size: 10000
trials_per_configuration: 3
classical:
  bounds:
    layers: [ 2, 3, 4 ]
    neurons: [ 8, 16, 32, 64 ]
    learning_rate: [ 0.03, 0.01, 0.003, 0.001, 0.0003 ]
quantum:
  trainable_entanglements: yes
  bounds:
    layers: [ 1, 3, 5, 7, 9 ]
    qubits: [ 4 ]
    rotations: [ [ x, y ] ]
    entanglements: [ ladder, double ladder, full, none ] # brick
    learning_rate: [ 0.3, 0.01, 0.03, 0.01, 0.003 ]
environment:
  name: CartPole-v1 # CartPole-v1, Acrobot-v1 or MountainCar-v0
  render_mode: human
  render: no
training:
  early_stop: 50
  batch_size: 16
  optimizer: adam
  loss: mse
  max_steps: 100
  max_eval_steps: 1000
  eval_episodes: 5
  episodes: 1000
  epsilon:
    end: 0.01
    start: 1
    change: .996
